### ISSUE TITLE
(Navajo) "Compilation in progress" error on logging into SLC

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#208]
I occasionally get this error when logging into SLC. It's always on a "first" type of situation.
Stacktrace:

12:52:11 NavajoLog - Compilation in progress
12:52:11 c.d.n.s.Dispatcher - Error: 
com.dexels.navajo.script.api.SystemException: Compilation in progress
	at com.dexels.navajo.server.GenericHandler.doService(GenericHandler.java:497) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.ServiceHandler.construct(ServiceHandler.java:68) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.persistence.impl.PersistenceManagerImpl.get(PersistenceManagerImpl.java:156) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.dispatch(Dispatcher.java:473) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.processNavajo(Dispatcher.java:1056) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.handle(Dispatcher.java:830) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.LocalClientDispatcherWrapper.handleInternal(LocalClientDispatcherWrapper.java:73) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.execute(TmlContinuationRunner.java:99) [com.dexels.navajo.listeners.continuations/:na]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.run(TmlContinuationRunner.java:165) [com.dexels.navajo.listeners.continuations/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [na:1.6.0_38]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6.0_38]
	at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_38]
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_38]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_38]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_38]
Caused by: java.lang.IllegalStateException: Compilation in progress
	at com.sun.tools.javac.api.JavacTool.beginContext(JavacTool.java:148) ~[na:na]
	at com.sun.tools.javac.api.JavacTaskImpl.beginContext(JavacTaskImpl.java:172) ~[na:na]
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:111) ~[na:na]
	at com.dexels.osgicompiler.internal.OSGiJavaCompilerImplementation.compile(OSGiJavaCompilerImplementation.java:129) ~[na:na]
	at com.dexels.navajo.compiler.tsl.internal.JavaCompilerComponent.compileJava(JavaCompilerComponent.java:60) ~[na:na]
	at com.dexels.navajo.compiler.tsl.internal.BundleCreatorComponent.createBundle(BundleCreatorComponent.java:140) ~[na:na]
	at com.dexels.navajo.compiler.tsl.internal.BundleCreatorComponent.getOnDemandScriptService(BundleCreatorComponent.java:546) ~[na:na]
	at com.dexels.navajo.server.GenericHandler.loadOnDemand(GenericHandler.java:578) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.GenericHandler.doService(GenericHandler.java:444) ~[com.dexels.navajo.core/:na]
	... 14 common frames omitted
12:52:11 c.d.n.s.Dispatcher - Error: 
java.lang.IllegalStateException: Compilation in progress
	at com.sun.tools.javac.api.JavacTool.beginContext(JavacTool.java:148) ~[na:na]
	at com.sun.tools.javac.api.JavacTaskImpl.beginContext(JavacTaskImpl.java:172) ~[na:na]
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:111) ~[na:na]
	at com.dexels.osgicompiler.internal.OSGiJavaCompilerImplementation.compile(OSGiJavaCompilerImplementation.java:129) ~[na:na]
	at com.dexels.navajo.compiler.tsl.internal.JavaCompilerComponent.compileJava(JavaCompilerComponent.java:60) ~[na:na]
	at com.dexels.navajo.compiler.tsl.internal.BundleCreatorComponent.createBundle(BundleCreatorComponent.java:140) ~[na:na]
	at com.dexels.navajo.compiler.tsl.internal.BundleCreatorComponent.getOnDemandScriptService(BundleCreatorComponent.java:546) ~[na:na]
	at com.dexels.navajo.server.GenericHandler.loadOnDemand(GenericHandler.java:578) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.GenericHandler.doService(GenericHandler.java:444) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.ServiceHandler.construct(ServiceHandler.java:68) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.persistence.impl.PersistenceManagerImpl.get(PersistenceManagerImpl.java:156) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.dispatch(Dispatcher.java:473) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.processNavajo(Dispatcher.java:1056) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.handle(Dispatcher.java:830) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.LocalClientDispatcherWrapper.handleInternal(LocalClientDispatcherWrapper.java:73) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.execute(TmlContinuationRunner.java:99) [com.dexels.navajo.listeners.continuations/:na]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.run(TmlContinuationRunner.java:165) [com.dexels.navajo.listeners.continuations/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [na:1.6.0_38]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6.0_38]
	at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_38]
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_38]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_38]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_38]

**Comment by cbrouwer** [comment]
With the new compiler in place, plus locking on simultaneous script compilation, this should no longer be a problem.
