### ISSUE TITLE
(Navajo) (Navajo-tester) (OSGi) Recompile on a directory doesn't work (anymore?)

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#289]
````
Script not found: discipline no such file: C:\Marte\CVS\sportlink-serv\navajo-tester\auxilary\scripts\discipline.xml
	at com.dexels.navajo.server.FileNavajoConfig.getApplicableFile(FileNavajoConfig.java:193) ~[na:na]
````

**Comment by flyaruu** [comment]
It seems to work in multitenant. Can you check if it still happens and if so, get a full stack trace?

**Comment by kharybdys** [comment]
Na verse pull van navajo, enterprise, sportlink.library, weghalen van de compiled scripts, herladen van target platform:

**Comment by kharybdys** [comment]
````
15:09:10.560 ERROR c.d.n.dev.servlet.CompileServlet - Error compiling scripts form servlet:
java.io.FileNotFoundException: Script not found: documents no such file: C:\Marte\CVS\sportlink-serv\navajo-tester\auxilary\scripts\documents.xml
	at com.dexels.navajo.server.FileNavajoConfig.getApplicableFile(FileNavajoConfig.java:193) ~[na:na]
	at com.dexels.navajo.server.FileNavajoConfig.getApplicableScriptFile(FileNavajoConfig.java:142) ~[na:na]
	at com.dexels.navajo.compiler.tsl.internal.BundleCreatorComponent.createBundle(BundleCreatorComponent.java:154) ~[na:na]
	at com.dexels.navajo.dev.servlet.CompileServlet.doGet(CompileServlet.java:54) ~[com.dexels.navajo.dev.console/:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:75) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:370) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_72]
15:09:11.399 DEBUG c.dexels.navajo.jsp.tags.InstanceTag - Tag Session Id: 4mlmnc2bwe146tmuokt5g83z setting to instance: null
````
