### ISSUE TITLE
(Navajo) Script in a directory with a dot in the name doesn't compile

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#291]
With thanks to the Autocompiler:
````
13:01:38.201 ERROR c.d.n.c.tsl.internal.AutoCompiler - Bundle creation problem for bundle: external/common/sport.nl/ProcessExportClubLogos
java.io.FileNotFoundException: Script not found: external/common/sport.nl/ProcessExportClubLogos no such file: C:\Marte\CVS\sportlink-serv\navajo-tester\auxilary\scripts\external\common\sport\nl\ProcessExportClubLogos.xml
	at com.dexels.navajo.server.FileNavajoConfig.getApplicableFile(FileNavajoConfig.java:193) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.FileNavajoConfig.getApplicableScriptFile(FileNavajoConfig.java:142) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.compiler.tsl.internal.BundleCreatorComponent.createBundle(BundleCreatorComponent.java:154) ~[com.dexels.navajo.compiler.tsl/:na]
	at com.dexels.navajo.compiler.tsl.internal.AutoCompiler.process(AutoCompiler.java:133) [com.dexels.navajo.compiler.tsl/:na]
	at com.dexels.navajo.compiler.tsl.internal.AutoCompiler$3.visitFile(AutoCompiler.java:95) [com.dexels.navajo.compiler.tsl/:na]
	at com.dexels.navajo.compiler.tsl.internal.AutoCompiler$3.visitFile(AutoCompiler.java:1) [com.dexels.navajo.compiler.tsl/:na]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:135) [na:1.7.0_72]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199) [na:1.7.0_72]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199) [na:1.7.0_72]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199) [na:1.7.0_72]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199) [na:1.7.0_72]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69) [na:1.7.0_72]
	at java.nio.file.Files.walkFileTree(Files.java:2602) [na:1.7.0_72]
	at java.nio.file.Files.walkFileTree(Files.java:2635) [na:1.7.0_72]
	at com.dexels.navajo.compiler.tsl.internal.AutoCompiler.scan(AutoCompiler.java:90) [com.dexels.navajo.compiler.tsl/:na]
	at com.dexels.navajo.compiler.tsl.internal.AutoCompiler.scan(AutoCompiler.java:83) [com.dexels.navajo.compiler.tsl/:na]
	at com.dexels.navajo.compiler.tsl.internal.AutoCompiler.access$1(AutoCompiler.java:81) [com.dexels.navajo.compiler.tsl/:na]
	at com.dexels.navajo.compiler.tsl.internal.AutoCompiler$2.run(AutoCompiler.java:64) [com.dexels.navajo.compiler.tsl/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_72]
````

**Comment by cbrouwer** [comment]
Internally, directories are seen as packages, which are seperated by dots. By allowing dots in the directory structure, this mechanism breaks on many levels (determining scripts, OSGi servic resolution, tenant-specific versions, etc). Therefore using dots in directory names is not supported for scripts.
