### ISSUE TITLE
(Navajo) (Tasks) Scripts don't compile?

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#304]
Looks like scripts won't get compiled when called from a task while no bundle available in OSGi yet.
Note that this might have had something to do with my test setup:
One generic version of a script, one KNKV version of that script.
Both KNKV and NHV have task triggers at the same time to execute this script.
KNKV did succesfully execute, NHV threw an error:
```
11:50:00.100 WARN  c.d.navajo.server.GenericHandler - Script not found from OSGi registry while OSGi is active
11:50:00.100 ERROR c.d.navajo.server.GenericHandler - No compiled script found, proceeding further is useless.
11:50:00.100 ERROR NavajoLog - Can not resolve script: ProcessTest
11:50:00.109 ERROR com.dexels.navajo.server.Dispatcher - Error: 
com.dexels.navajo.script.api.SystemException: Can not resolve script: ProcessTest
	at com.dexels.navajo.server.GenericHandler.doService(GenericHandler.java:509) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.ServiceHandler.construct(ServiceHandler.java:68) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.persistence.impl.PersistenceManagerImpl.get(PersistenceManagerImpl.java:164) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.dispatch(Dispatcher.java:487) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.processNavajo(Dispatcher.java:1027) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.handle(Dispatcher.java:742) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.scheduler.Task.run(Task.java:546) [com.dexels.navajo.enterprise/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_72]
Caused by: java.lang.RuntimeException: Can not resolve script: ProcessTest
	at com.dexels.navajo.server.GenericHandler.doService(GenericHandler.java:478) ~[com.dexels.navajo.core/:na]
	... 11 common frames omitted
11:50:00.111 ERROR com.dexels.navajo.server.Dispatcher - Error: 
java.lang.RuntimeException: Can not resolve script: ProcessTest
	at com.dexels.navajo.server.GenericHandler.doService(GenericHandler.java:478) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.ServiceHandler.construct(ServiceHandler.java:68) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.persistence.impl.PersistenceManagerImpl.get(PersistenceManagerImpl.java:164) ~[com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.dispatch(Dispatcher.java:487) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.processNavajo(Dispatcher.java:1027) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.handle(Dispatcher.java:742) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.scheduler.Task.run(Task.java:546) [com.dexels.navajo.enterprise/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_72]
```

**Comment by cbrouwer** [comment]
This might have been caused by the simultaneous compilation of the same script.
By now a lot of this code has been updated, and  simultaneous compilation should no longer be a problem.
If you can still reproduce, please re-open.
