### ISSUE TITLE
Hazelcast serializing bug

### ISSUE THREAD

**Issue by cbrouwer** [Dexels/navajo#307]
015-07-13 08:55:23,206 | ERROR | 70385959-6351884 | HazelcastTribeManager            | 290 - com.dexels.navajo.enterprise.hazelcast - 3.1.18 | com.hazelcast.nio.HazelcastSerializationException: Problem when serializing type 1
java.util.concurrent.ExecutionException: com.hazelcast.nio.HazelcastSerializationException: Problem when serializing type 1
	at com.hazelcast.core.DistributedTask.get(DistributedTask.java:157)
	at com.dexels.navajo.hazelcast.tribe.HazelcastTribeManager.askSomebody(HazelcastTribeManager.java:297)
	at com.dexels.navajo.hazelcast.tribe.HazelcastTribeManager.tribalAfterWebServiceRequest(HazelcastTribeManager.java:257)
	at com.dexels.navajo.scheduler.WebserviceListenerRegistry.afterWebservice(WebserviceListenerRegistry.java:256)
	at com.dexels.navajo.scheduler.WebserviceListenerRegistry.afterWebservice(WebserviceListenerRegistry.java:176)
	at com.dexels.navajo.server.Dispatcher.finalizeService(Dispatcher.java:1195)
	at com.dexels.navajo.server.Dispatcher.processNavajo(Dispatcher.java:1079)
	at com.dexels.navajo.server.Dispatcher.handle(Dispatcher.java:742)
	at com.dexels.navajo.scheduler.Task.run(Task.java:545)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.hazelcast.nio.HazelcastSerializationException: Problem when serializing type 1
	at com.hazelcast.nio.AbstractSerializer.toObject(AbstractSerializer.java:128)
	at com.hazelcast.nio.AbstractSerializer.toObject(AbstractSerializer.java:156)
	at com.hazelcast.nio.Serializer.readObject(Serializer.java:75)
	at com.hazelcast.impl.ThreadContext.toObject(ThreadContext.java:135)
	at com.hazelcast.nio.IOUtil.toObject(IOUtil.java:163)
	at com.hazelcast.impl.ExecutorManager$RequestExecutor.run(ExecutorManager.java:312)
	at com.hazelcast.impl.executor.ParallelExecutorService$ParallelExecutorImpl$ExecutionSegment.run(ParallelExecutorService.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.impl.ExecutorThreadFactory$1.run(ExecutorThreadFactory.java:45)
Caused by: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.getLong(Field.java:611)
	at java.io.ObjectStreamClass.getDeclaredSUID(ObjectStreamClass.java:1663)
	at java.io.ObjectStreamClass.access$700(ObjectStreamClass.java:72)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:480)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:468)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:468)
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:365)
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:602)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readUnshared(ObjectInputStream.java:461)
	at com.hazelcast.nio.DefaultSerializer$ObjectSerializer.readNormal(DefaultSerializer.java:410)
	at com.hazelcast.nio.DefaultSerializer$ObjectSerializer.read(DefaultSerializer.java:380)
	at com.hazelcast.nio.DefaultSerializer.read(DefaultSerializer.java:138)
	at com.hazelcast.nio.CustomSerializerAdapter.read(CustomSerializerAdapter.java:32)
	at com.hazelcast.nio.AbstractSerializer.toObject(AbstractSerializer.java:121)
	... 10 more
Caused by: java.lang.NullPointerException
	at com.dexels.navajo.server.enterprise.tribe.DefaultNavajoWrap.<clinit>(DefaultNavajoWrap.java:30)
	... 42 more

**Comment by cbrouwer** [comment]
Should be fixed now
