### ISSUE TITLE
Multi-tenant incompatability in Message comparator

### ISSUE THREAD

**Issue by aschoneveld** [Dexels/navajo#308]
For example GenericRanking in Sportlink. This does not work under multi-tenancy.

**Comment by aschoneveld** [comment]
Fixed

**Comment by cbrouwer** [comment]
Few exceptions:

2015-08-31 09:23:47,921 | ERROR | normalPool_36    | BaseMessageImpl                  | 116 - com.dexels.navajo.document - 3.0.24 | Error: 
java.lang.NullPointerException
	at com.dexels.sportlink.comparison.Ranking.compare(Ranking.java:484)[166:com.sportlink.adapters:3.0.56]
	at com.dexels.sportlink.comparison.Ranking.compare(Ranking.java:1)[166:com.sportlink.adapters:3.0.56]
	at com.dexels.navajo.document.base.BaseMessageImpl.compareTo(BaseMessageImpl.java:1398)[116:com.dexels.navajo.document:3.0.24]
	at com.dexels.navajo.document.base.BaseMessageImpl.compareTo(BaseMessageImpl.java:1)[116:com.dexels.navajo.document:3.0.24]
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:325)[:1.8.0_66-internal]
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)[:1.8.0_66-internal]
	at java.util.Arrays.sort(Arrays.java:1312)[:1.8.0_66-internal]
	at java.util.Arrays.sort(Arrays.java:1506)[:1.8.0_66-internal]
	at java.util.ArrayList.sort(ArrayList.java:1454)[:1.8.0_66-internal]
	at java.util.Collections.sort(Collections.java:141)[:1.8.0_66-internal]
	at com.dexels.navajo.document.base.BaseMessageImpl.getChildren(BaseMessageImpl.java:1313)[116:com.dexels.navajo.document:3.0.24]
	at com.dexels.navajo.document.base.BaseNode.printElement(BaseNode.java:115)[116:com.dexels.navajo.document:3.0.24]
	at com.dexels.navajo.document.base.BaseNode.printElement(BaseNode.java:130)[116:com.dexels.navajo.document:3.0.24]
	at com.dexels.navajo.document.base.BaseNode.write(BaseNode.java:276)[116:com.dexels.navajo.document:3.0.24]
	at com.dexels.navajo.server.listener.http.impl.BaseRequestImpl.writeOutput(BaseRequestImpl.java:272)[123:com.dexels.navajo.listeners.external:2.1.8]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.endTransaction(TmlContinuationRunner.java:69)[126:com.dexels.navajo.listeners.continuations:2.0.14]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.execute(TmlContinuationRunner.java:110)[126:com.dexels.navajo.listeners.continuations:2.0.14]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.run(TmlContinuationRunner.java:167)[126:com.dexels.navajo.listeners.continuations:2.0.14]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_66-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_66-internal]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_66-internal]



2015-08-31 09:28:29,053 | WARN  | 1006109016-35456 | GrusProviderImpl                 | 134 - com.dexels.navajo.adapters.resource - 2.0.28 | No datasource found for instance: null and name: sportlinkkernel datasource keys: [navajostore, navajo.resource.sportlink, competition, sportlink, navajo.resource.navajostore, dashboard, authentication]
java.lang.Exception
	at com.dexels.navajo.adapter.resource.provider.impl.GrusProviderImpl.getInstanceDataSource(GrusProviderImpl.java:135)[134:com.dexels.navajo.adapters.resource:2.0.28]
	at com.dexels.navajo.adapter.resource.provider.impl.GrusProviderImpl.requestConnection(GrusProviderImpl.java:177)[134:com.dexels.navajo.adapters.resource:2.0.28]
	at com.dexels.navajo.adapter.SQLMap.createConnection(SQLMap.java:926)[132:com.dexels.navajo.adapters:2.2.24]
	at com.dexels.navajo.adapter.SQLMap.getDBResultSet(SQLMap.java:1047)[132:com.dexels.navajo.adapters:2.2.24]
	at com.dexels.navajo.adapter.SQLMap.getResultSet(SQLMap.java:1250)[132:com.dexels.navajo.adapters:2.2.24]
	at com.dexels.navajo.adapter.SQLMap.getResultSet(SQLMap.java:1172)[132:com.dexels.navajo.adapters:2.2.24]
	at com.dexels.navajo.adapter.SQLMap.getColumnValue(SQLMap.java:755)[132:com.dexels.navajo.adapters:2.2.24]
	at com.dexels.sportlink.comparison.GenericRanking.getRankingOrder(GenericRanking.java:60)[166:com.sportlink.adapters:3.0.56]
	at com.dexels.sportlink.comparison.GenericRanking.compare_implementation(GenericRanking.java:96)[166:com.sportlink.adapters:3.0.56]
	at com.dexels.sportlink.comparison.GenericRanking.default_compare(GenericRanking.java:87)[166:com.sportlink.adapters:3.0.56]
	at com.dexels.sportlink.comparison.Ranking.compare(Ranking.java:525)[166:com.sportlink.adapters:3.0.56]
	at com.dexels.sportlink.comparison.Ranking.compare(Ranking.java:1)[166:com.sportlink.adapters:3.0.56]
	at com.dexels.navajo.document.base.BaseMessageImpl.compareTo(BaseMessageImpl.java:1398)[116:com.dexels.navajo.document:3.0.24]
	at com.dexels.navajo.document.base.BaseMessageImpl.compareTo(BaseMessageImpl.java:1)[116:com.dexels.navajo.document:3.0.24]
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:325)[:1.8.0_66-internal]
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)[:1.8.0_66-internal]
	at java.util.Arrays.sort(Arrays.java:1312)[:1.8.0_66-internal]
	at java.util.Arrays.sort(Arrays.java:1506)[:1.8.0_66-internal]
	at java.util.ArrayList.sort(ArrayList.java:1454)[:1.8.0_66-internal]
	at java.util.Collections.sort(Collections.java:141)[:1.8.0_66-internal]
	at com.dexels.navajo.document.base.BaseMessageImpl.getChildren(BaseMessageImpl.java:1313)[116:com.dexels.navajo.document:3.0.24]
	at com.dexels.navajo.document.base.BaseNode.printElement(BaseNode.java:115)[116:com.dexels.navajo.document:3.0.24]
	at com.dexels.navajo.document.base.BaseNode.printElement(BaseNode.java:130)[116:com.dexels.navajo.document:3.0.24]
	at com.dexels.navajo.document.base.BaseNode.printElement(BaseNode.java:130)[116:com.dexels.navajo.document:3.0.24]
	at com.dexels.navajo.document.base.BaseNode.write(BaseNode.java:276)[116:com.dexels.navajo.document:3.0.24]
	at com.dexels.navajo.adapter.NavajoMap.continueAfterRun(NavajoMap.java:1306)[132:com.dexels.navajo.adapters:2.2.24]
	at com.dexels.navajo.adapter.NavajoMap.run(NavajoMap.java:1411)[132:com.dexels.navajo.adapters:2.2.24]
	at com.dexels.navajo.adapter.NavajoMap.setDoSend(NavajoMap.java:846)[132:com.dexels.navajo.adapters:2.2.24]
	at com.dexels.navajo.adapter.NavajoMap.setDoSend(NavajoMap.java:797)[132:com.dexels.navajo.adapters:2.2.24]
	at external.competition.ProcessGetPoolStandings_KNVB.execute(ProcessGetPoolStandings_KNVB.java:231)[251:navajo.script.external/competition/ProcessGetPoolStandings|KNVB:1.0.0.20150831091748]
	at com.dexels.navajo.mapping.CompiledScript.run(CompiledScript.java:455)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.GenericHandler.doService(GenericHandler.java:480)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.ServiceHandler.construct(ServiceHandler.java:68)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.persistence.impl.PersistenceManagerImpl.get(PersistenceManagerImpl.java:164)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.Dispatcher.dispatch(Dispatcher.java:494)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.Dispatcher.processNavajo(Dispatcher.java:1043)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.Dispatcher.handle(Dispatcher.java:760)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.adapter.NavajoMap.run(NavajoMap.java:1407)[132:com.dexels.navajo.adapters:2.2.24]
	at com.dexels.navajo.adapter.NavajoMap.setDoSend(NavajoMap.java:846)[132:com.dexels.navajo.adapters:2.2.24]
	at com.dexels.navajo.adapter.NavajoMap.setDoSend(NavajoMap.java:797)[132:com.dexels.navajo.adapters:2.2.24]
	at clubsites.competition.CompetitionStandings.execute(CompetitionStandings.java:109)[249:navajo.script.clubsites/competition/CompetitionStandings:1.0.0.20150831091747]
	at com.dexels.navajo.mapping.CompiledScript.run(CompiledScript.java:455)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.GenericHandler.doService(GenericHandler.java:480)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.ServiceHandler.construct(ServiceHandler.java:68)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.persistence.impl.PersistenceManagerImpl.get(PersistenceManagerImpl.java:164)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.Dispatcher.dispatch(Dispatcher.java:494)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.Dispatcher.processNavajo(Dispatcher.java:1043)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.Dispatcher.handle(Dispatcher.java:760)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.adapter.NavajoMap.run(NavajoMap.java:1407)[132:com.dexels.navajo.adapters:2.2.24]
	at com.dexels.navajo.adapter.NavajoMap.setDoSend(NavajoMap.java:846)[132:com.dexels.navajo.adapters:2.2.24]
	at com.dexels.navajo.adapter.NavajoMap.setDoSend(NavajoMap.java:797)[132:com.dexels.navajo.adapters:2.2.24]
	at clubsites.nl.standbasis.execute(standbasis.java:80)[245:navajo.script.clubsites/nl/standbasis:1.0.0.20150831091746]
	at com.dexels.navajo.mapping.CompiledScript.run(CompiledScript.java:455)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.GenericHandler.doService(GenericHandler.java:480)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.ServiceHandler.construct(ServiceHandler.java:68)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.persistence.impl.PersistenceManagerImpl.get(PersistenceManagerImpl.java:164)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.Dispatcher.dispatch(Dispatcher.java:494)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.Dispatcher.processNavajo(Dispatcher.java:1043)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.Dispatcher.handle(Dispatcher.java:819)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.LocalClientDispatcherWrapper.handleInternal(LocalClientDispatcherWrapper.java:80)[122:com.dexels.navajo.core:3.9.0]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.execute(TmlContinuationRunner.java:99)[126:com.dexels.navajo.listeners.continuations:2.0.14]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.run(TmlContinuationRunner.java:167)[126:com.dexels.navajo.listeners.continuations:2.0.14]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_66-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_66-internal]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_66-internal]

**Comment by aschoneveld** [comment]
Should be fixed in scripts that use this function. A param "Tenant" must be defined in the Pool message (see competition/ProcessGetPoolStanding as an example)

**Comment by eversteeg** [comment]
Should be fixed in all scripts now
