### ISSUE TITLE
WorkflowManager.getInstance null on running system

### ISSUE THREAD

**Issue by cbrouwer** [Dexels/navajo#312]
2015-07-27 16:31:58,501 | WARN  | cached.thread-20 | WorkFlowManager                  | 201 - com.dexels.navajo.enterprise - 3.2.66 | No active WorkFlowManager found
java.lang.Exception
	at com.dexels.navajo.workflow.WorkFlowManager.getInstance(WorkFlowManager.java:384)[201:com.dexels.navajo.enterprise:3.2.66]
	at com.dexels.navajo.workflow.tribe.SingleAnswer.constructSummary(SingleAnswer.java:22)[201:com.dexels.navajo.enterprise:3.2.66]
	at com.dexels.navajo.workflow.tribe.SingleAnswer.<init>(SingleAnswer.java:17)[201:com.dexels.navajo.enterprise:3.2.66]
	at com.dexels.navajo.workflow.tribe.SingleRequest.getAnswer(SingleRequest.java:67)[201:com.dexels.navajo.enterprise:3.2.66]
	at com.dexels.navajo.hazelcast.tribe.HazelcastRequest.call(HazelcastRequest.java:31)[208:com.dexels.navajo.enterprise.hazelcast:3.1.22]
	at com.dexels.navajo.hazelcast.tribe.HazelcastRequest.call(HazelcastRequest.java:1)[208:com.dexels.navajo.enterprise.hazelcast:3.1.22]
	at com.hazelcast.impl.ExecutorManager$RequestExecutor.run(ExecutorManager.java:317)[110:com.hazelcast:2.6.9]
	at com.hazelcast.impl.executor.ParallelExecutorService$ParallelExecutorImpl$ExecutionSegment.run(ParallelExecutorService.java:242)[110:com.hazelcast:2.6.9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_45-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_45-internal]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_45-internal]

**Comment by cbrouwer** [comment]
Possibly related:
MXBean not found, so deregister of: navajo.service:type= : Navajo WorkFlow Manager failed (navajo.service:type=Navajo WorkFlow Manager,instance=production-knvb-1). Continuing

**Comment by cbrouwer** [comment]
Fixed in Dexels/enterprise@f040d247b2ea6f361b70b621d3b3dc22de0c2229
