### ISSUE TITLE
GetMailNavajo assumes Multipart messages.

### ISSUE THREAD

**Issue by flyaruu** [Dexels/navajo#319]
When faced with a simple message, the following happens:

javax.mail.MessagingException: Missing start boundary
  	at javax.mail.internet.MimeMultipart.parsebm(MimeMultipart.java:872)
  	at javax.mail.internet.MimeMultipart.parse(MimeMultipart.java:493)
  	at javax.mail.internet.MimeMultipart.getCount(MimeMultipart.java:240)
  	at com.dexels.navajo.tipi.mail.functions.GetMailNavajo.evaluate(GetMailNavajo.java:49)
  	at com.dexels.navajo.parser.FunctionInterface.evaluateWithTypeChecking(FunctionInterface.java:292)[122:com.dexels.navajo.core:3.4.4]
  	at com.dexels.navajo.parser.ASTFunctionNode.interpret(ASTFunctionNode.java:189)[122:com.dexels.navajo.core:3.4.4]
  	at com.dexels.navajo.parser.ASTFunctionNode.interpret(ASTFunctionNode.java:185)[122:com.dexels.navajo.core:3.4.4]
  	at com.dexels.navajo.parser.ASTFunctionNode.interpret(ASTFunctionNode.java:185)[122:com.dexels.navajo.core:3.4.4]
  	at com.dexels.navajo.parser.Expression.evaluate(Expression.java:66)[122:com.dexels.navajo.core:3.4.4]

**Comment by flyaruu** [comment]
Fixed
