### ISSUE TITLE
Hazelcast ClassNotFound

### ISSUE THREAD

**Issue by cbrouwer** [Dexels/navajo#329]
Probably direct consequence of upgrading to Hazelcast 3.5 and the refactoring of Hazelcast executors.

11:11:27.063 ERROR c.h.e.i.o.MemberCallableTaskOperation - [192.168.122.1]:5701 [development_chrischris] [3.5.1] java.lang.ClassNotFoundException: com.dexels.navajo.sharedstore.map.TribalMapSignal cannot be found by com.dexels.navajo.listeners.continuations_2.0.15.qualifier
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.dexels.navajo.sharedstore.map.TribalMapSignal cannot be found by com.dexels.navajo.listeners.continuations_2.0.15.qualifier
	at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:201) ~[com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:41) ~[com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:276) ~[com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:200) ~[com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.executor.impl.operations.BaseCallableTaskOperation.getCallable(BaseCallableTaskOperation.java:81) ~[com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.executor.impl.operations.BaseCallableTaskOperation.beforeRun(BaseCallableTaskOperation.java:63) ~[com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:131) ~[com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:380) [com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThreadIfPossible(ClassicOperationExecutor.java:342) [com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:247) [com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:231) [com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:198) [com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:168) [com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:277) [com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.executor.impl.ExecutorServiceProxy.submitToMember(ExecutorServiceProxy.java:302) [com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.executor.impl.ExecutorServiceProxy.submitToMembers(ExecutorServiceProxy.java:320) [com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.executor.impl.ExecutorServiceProxy.submitToAllMembers(ExecutorServiceProxy.java:328) [com.hazelcast_3.5.1.jar:3.5.1]
	at com.dexels.navajo.hazelcast.tribe.HazelcastTribeManager.broadcast(HazelcastTribeManager.java:226) [com.dexels.navajo.enterprise.hazelcast/:na]
	at com.dexels.navajo.sharedstore.map.SharedTribalMap.registerMap(SharedTribalMap.java:67) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.persistence.impl.PersistenceManagerImpl.init(PersistenceManagerImpl.java:133) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.persistence.impl.PersistenceManagerImpl.get(PersistenceManagerImpl.java:152) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.dispatch(Dispatcher.java:494) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.processNavajo(Dispatcher.java:1042) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.Dispatcher.handle(Dispatcher.java:819) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.LocalClientDispatcherWrapper.handleInternal(LocalClientDispatcherWrapper.java:80) [com.dexels.navajo.core/:na]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.execute(TmlContinuationRunner.java:99) [com.dexels.navajo.listeners.continuations/:na]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.run(TmlContinuationRunner.java:167) [com.dexels.navajo.listeners.continuations/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: com.dexels.navajo.sharedstore.map.TribalMapSignal cannot be found by com.dexels.navajo.listeners.continuations_2.0.15.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337) ~[na:na]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160) ~[na:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_79]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:568) ~[na:na]
	at org.ops4j.pax.swissbox.core.BundleClassLoader.findClass(BundleClassLoader.java:176) ~[org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_79]
	at org.ops4j.pax.swissbox.core.BundleClassLoader.loadClass(BundleClassLoader.java:192) ~[org.ops4j.pax.web.pax-web-jetty-bundle_3.1.3.jar:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_79]
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:125) ~[com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:114) ~[com.hazelcast_3.5.1.jar:3.5.1]
	at com.hazelcast.nio.IOUtil$1.resolveClass(IOUtil.java:113) ~[com.hazelcast_3.5.1.jar:3.5.1]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370) ~[na:1.7.0_79]
	at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:196) ~[com.hazelcast_3.5.1.jar:3.5.1]
	... 31 common frames omitted

**Comment by cbrouwer** [comment]
Fixed in Dexels/enterprise@259645c7ad5df5327d58a571c83f3324c7e1f474
