### ISSUE TITLE
Mongo Access Store has a problem with big navajo messages

### ISSUE THREAD

**Issue by flyaruu** [Dexels/navajo#384]
(Noticed on local running development)

[instance-1/1470243600227-10] INFO NavajoLog - EXCEPTIONERROR OCCURED, BUT WAS EXCEPTION HANDLING WAS SET TO FALSE, RETURNING....
[async_3] INFO stats - Finished 1470243600227-10 (external/common/sportnl/ProcessExportSportNLData) in 262084ms
[Navajo StatisticsRunner] ERROR com.dexels.navajo.mongo.accessstore.MongoStore - Exception in storing access objects. Writing access to file... {}
org.bson.BsonSerializationException: Size 52320612 is larger than MaxDocumentSize 16793600.
    at org.bson.BsonBinaryWriter.backpatchSize(BsonBinaryWriter.java:367)
    at org.bson.BsonBinaryWriter.doWriteEndArray(BsonBinaryWriter.java:142)
    at org.bson.AbstractBsonWriter.writeEndArray(AbstractBsonWriter.java:338)
    at com.dexels.navajo.mongo.document.MessageCodec.encode(MessageCodec.java:78)
    at com.dexels.navajo.mongo.document.MessageCodec.encode(MessageCodec.java:1)
    at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
    at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:175)
    at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
    at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:172)
    at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
    at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:131)
    at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45)
    at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
    at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
    at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:101)
    at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:43)
    at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBodyWithMetadata(BaseWriteCommandMessage.java:129)
    at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:160)
    at com.mongodb.connection.WriteCommandProtocol.sendMessage(WriteCommandProtocol.java:220)
    at com.mongodb.connection.WriteCommandProtocol.execute(WriteCommandProtocol.java:101)
    at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:67)
    at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:37)
    at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
    at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
    at com.mongodb.connection.DefaultServerConnection.insertCommand(DefaultServerConnection.java:118)
    at com.mongodb.operation.MixedBulkWriteOperation$Run$2.executeWriteCommandProtocol(MixedBulkWriteOperation.java:456)
    at com.mongodb.operation.MixedBulkWriteOperation$Run$RunExecutor.execute(MixedBulkWriteOperation.java:647)
    at com.mongodb.operation.MixedBulkWriteOperation$Run.execute(MixedBulkWriteOperation.java:402)
    at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:180)
    at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:169)
    at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:232)
    at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:223)
    at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:169)
    at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:75)
    at com.mongodb.Mongo.execute(Mongo.java:827)
    at com.mongodb.Mongo$2.execute(Mongo.java:810)
    at com.mongodb.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:323)
    at com.mongodb.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:311)
    at com.dexels.navajo.mongo.accessstore.MongoStore.storeAccess(MongoStore.java:308)
    at com.dexels.navajo.server.statistics.StatisticsRunner.worker(StatisticsRunner.java:224)
    at com.dexels.navajo.server.GenericThread.run(GenericThread.java:129)
    at java.lang.Thread.run(Thread.java:745)

**Comment by cbrouwer** [comment]
This is due to the document size limit of mongo of [16 mb](https://docs.mongodb.com/manual/reference/limits/#bson-documents).

I don't really see an easy fix for this. Always storing access objects in GridFS seems wasteful and unnecessary. There is also no easy way of telling in java that a document will exceed this limit. 

Due to the unlikelihood of this happening (it's the first time I've seen this since storing access objects in Mongo since 2014), I'd say won't fix for now.
