### ISSUE TITLE
(Mongo) Cannot call QueryMongoAdapter when inputMessage does not exist

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#446]
Why would the following code not be allowed to work? (Note the commented out part that makes it work)
```
<?xml version="1.0" encoding="UTF-8"?>
<navascript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.navajo.nl/schemas/navascript.xsd">
    
    <include script="external/mongo/include/IncludeMongoSeason"/>
    
<!--    <message name="Season"/> -->

    <map.navajomap useCurrentOutDoc="true">
        <navajomap.createproperty name="'/__Mongo__/Multiple'" value="true" />
        <navajomap.callwebservice name="'mongo/ProcessQueryMongo'"/>
        <navajomap.messagePointer value="'/Season'"/>

        <message name="Seasons" type="simple">
            <message name="Season">
                <navajomap.messages>
                    <property name="SeasonId" type="string">
                        <expression value="$property('seasonid')"/>
                    </property>
                    <property name="Description" type="string">
                        <expression value="$property('seasondescription')"/>
                    </property>
                    <property name="FromDate" type="date">
                        <expression value="$property('fromdate')"/>
                    </property>
                    <property name="ToDate" type="date">
                        <expression value="$property('todate')"/>
                    </property>
                    <property name="ReferenceDate" type="date">
                        <expression value="$property('referencedate')"/>
                    </property>
                </navajomap.messages>
            </message>
        </message>
    </map.navajomap>

    <antimessage name="__Mongo__"/>
</navascript>
```
Exception is
```
com.dexels.navajo.script.api.UserException: Unable to find message Season in indoc!
	at com.dexels.navajo.mongo.adapter.base.BaseMongoAdapter.getInputMessage(BaseMongoAdapter.java:184)
	at com.dexels.navajo.mongo.adapter.QueryMongoAdapter.store(QueryMongoAdapter.java:25)
	at com.dexels.navajo.mapping.MappingUtils.callStoreMethod(MappingUtils.java:629)
	at mongo.ProcessQueryMongo.execute(ProcessQueryMongo.java:73)
```

**Comment by cbrouwer** [comment]
The QueryMongoAdapter always requires an Input message. This can be just the message (e.g.`<message name="Season"/>`) which translates to querying `{}`, or a message with properties with filters the query.

One could argue that we should interpret a missing input message as a 'give me everything'-query. However this could be tricky in situations where you simply forgot or where the message was not passed properly by a calling script - in which case giving 'everything' might cause security issues by giving more/different data than what the user is allowed to see.

Thus, this is the expected and desired behavior.
