### ISSUE TITLE
Use <break> construct to throw ConditionError from Navascript

### ISSUE THREAD

**Issue by aschoneveld** [Dexels/navajo#457]
It is convenient to be able to throw a ConditionError somewhere in the script.
Suggestion is to use <break> in order to do this.
Currently <break> can throw a normal error if "error" attribute is specified.
By adding option for "conditionerror" icm with "errorcode" it's easy to generate a Conditionerror:
`<break conditionerror="'Something is missing'" errorcode="42"/>`

**Comment by DimitrisD** [comment]
Will this suffice?

Example of happy usage:

Using:

```xml
<break conditionError="Something went wrong" errorCode="300"/>
```

the output is:

```
11:25:27.111 DEBUG com.dexels.navajo.script.api.Access - ConditionError break at line: 22
11:25:27.112 DEBUG com.dexels.navajo.script.api.Access - ErrorCode: 300 - Something went wrong
--------- NAVAJO CONSOLE OUTPUT: defaultPackage.InitHello
ConditionError break at line: 22
ErrorCode: 300 - Something went wrong
--------- NAVAJO CONSOLE OUTPUT
11:25:27.112 ERROR com.dexels.navajo.server.Dispatcher - Generating error message for: 
com.dexels.navajo.script.api.UserException: KNVB
	at defaultPackage.InitHello.execute(InitHello.java:120)
	at com.dexels.navajo.mapping.CompiledScript.run(CompiledScript.java:456)
	at com.dexels.navajo.server.GenericHandler.doService(GenericHandler.java:476)
	at com.dexels.navajo.server.ServiceHandler.construct(ServiceHandler.java:68)
	at com.dexels.navajo.persistence.impl.PersistenceManagerImpl.get(PersistenceManagerImpl.java:164)
	at com.dexels.navajo.server.Dispatcher.dispatch(Dispatcher.java:455)
	at com.dexels.navajo.server.Dispatcher.processNavajo(Dispatcher.java:1032)
	at com.dexels.navajo.server.Dispatcher.handle(Dispatcher.java:781)
	at com.dexels.navajo.server.LocalClientDispatcherWrapper.handleInternal(LocalClientDispatcherWrapper.java:79)
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.execute(TmlContinuationRunner.java:111)
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.run(TmlContinuationRunner.java:183)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748) 
```

If the developer specifies only one of the errorCode or conditionError, then an exception is thrown while compiling the script.

**Comment by kharybdys** [comment]
Now just to replace the description by a query on the code from validation.properties so you're internationalized!

**Comment by cbrouwer** [comment]
Descriptions of validation errors are more of a default/internal description. Clients should always retrieve the validation.properties with their own locale and use this for actual displaying the validation error.
