### ISSUE TITLE
Allow for an internal field to be a List<Mappable> instead of an Mappable[], look at the returnType of the getter

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#531]
I'm writing new Adapters (Mappable) with the option to get an array of Mappable subresults. Even though I've made the field containing the List of subresults private, MappingUtils looks at the type of the field to determine whether this should support looping (isArrayAtr in TslCompiler, determineTypeForField in MappingUtils), regardless of the return type of the accompanying getter.

I would like for the code to check the getter type and not the field, allowing for both not having the field (at all) and for differences in types. This adheres more to the Java Standard too.

**Comment by kharybdys** [comment]
As a simple version, take the following webservice
```
<?xml version="1.0" encoding="UTF-8"?>
<navascript>

    <map.count rowCount="10">
        <message name="Row">
            <count.rows>
                <property name="RowNumber">
                    <expression value="$rowNumber"/>
                </property>
            </count.rows>
        </message>
    </map.count>
    
</navascript>
```
together with the following two new adapters
```
package com.dexels.navajo.adapter;

import com.dexels.navajo.script.api.Access;
import com.dexels.navajo.script.api.Mappable;
import com.dexels.navajo.script.api.MappableException;
import com.dexels.navajo.script.api.UserException;

public class RowMap implements Mappable 
{
    private int rowNr;
    
    public RowMap( int rowNr )
    {
        this.rowNr = rowNr;
    }

    @Override
    public void load( Access access ) throws MappableException, UserException
    {
    }

    @Override
    public void store() throws MappableException, UserException 
    {
    }

    @Override
    public void kill() 
    {
    }
    
    public int getRowNumber()
    {
        return rowNr;
    }
}
```
and 
```
package com.dexels.navajo.adapter;

import java.util.ArrayList;
import java.util.List;

import com.dexels.navajo.script.api.Access;
import com.dexels.navajo.script.api.Mappable;
import com.dexels.navajo.script.api.MappableException;
import com.dexels.navajo.script.api.UserException;

public class CountAdapter implements Mappable 
{
    private int rowCount = -1;
    // Only there for the TSL Compiler
    public RowMap[] rows = null;

    @Override
    public void load( Access access ) throws MappableException, UserException
    {
    }

    @Override
    public void store() throws MappableException, UserException 
    {
    }

    @Override
    public void kill() 
    {
    }
    
    public void setRowCount( int rowCount )
    {
        this.rowCount = rowCount;
    }

    public RowMap[] getRows() throws UserException
    {
        if( rowCount < 0 )
        {
            throw new UserException( "Specify number of rows to generate first" );
        }
        else
        {
            List<RowMap> rows = new ArrayList<RowMap>();
            for( int i = 0; i < rowCount; i++ ) 
            {
                rows.add( new RowMap( i ) );
            }
            return rows.toArray( new RowMap[rows.size()] );
        }
    }
}
```
and the configuration in adapters.xml:
```
    <map>
        <tagname>count</tagname>
        <object>com.dexels.navajo.adapter.CountAdapter</object>
        <values>
            <value name="rowCount" required="true" direction="in"/>
            <value name="rows" map="row []" required="false" direction="out" />
        </values>
    </map>
    <map>
        <tagname>row</tagname>
        <object>com.dexels.navajo.adapter.RowMap</object>
        <values>
            <value name="rowNumber" required="false" direction="out"/>
        </values>
    </map>
```

This version works, this is the current situation.

**Comment by kharybdys** [comment]
All changes are to CountAdapter.

**Comment by kharybdys** [comment]
This version:
```
package com.dexels.navajo.adapter;

import java.util.ArrayList;
import java.util.List;

import com.dexels.navajo.script.api.Access;
import com.dexels.navajo.script.api.Mappable;
import com.dexels.navajo.script.api.MappableException;
import com.dexels.navajo.script.api.UserException;

public class CountAdapter implements Mappable 
{
    private int rowCount = -1;
    private List<RowMap> rows = null;

    @Override
    public void load( Access access ) throws MappableException, UserException
    {
    }

    @Override
    public void store() throws MappableException, UserException 
    {
    }

    @Override
    public void kill() 
    {
    }
    
    public void setRowCount( int rowCount )
    {
        this.rowCount = rowCount;
    }

    public RowMap[] getRows() throws UserException
    {
        if( rowCount < 0 )
        {
            throw new UserException( "Specify number of rows to generate first" );
        }
        else
        {
            List<RowMap> rows = new ArrayList<RowMap>();
            for( int i = 0; i < rowCount; i++ ) 
            {
                rows.add( new RowMap( i ) );
            }
            return rows.toArray( new RowMap[rows.size()] );
        }
    }
}
```
Differs only in the type of the internal field and although that is private, results in the following exception:
```
2020-12-14 15:58:08,192 | ERROR | /1607957884148-1 | Dispatcher                       | 23 - com.dexels.navajo.core - 5.3.63.qualifier | Error: 
com.dexels.navajo.script.api.SystemException: class [Lcom.dexels.navajo.adapter.RowMap; cannot be cast to class java.util.List ([Lcom.dexels.navajo.adapter.RowMap; is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6cfeb5f3; java.util.List is in module java.base of loader 'bootstrap')
	at com.dexels.navajo.server.GenericHandler.doService(GenericHandler.java:447)[23:com.dexels.navajo.core:5.3.63.qualifier]
	at com.dexels.navajo.server.Dispatcher.dispatch(Dispatcher.java:353)[23:com.dexels.navajo.core:5.3.63.qualifier]
	at com.dexels.navajo.server.Dispatcher.processNavajo(Dispatcher.java:905)[23:com.dexels.navajo.core:5.3.63.qualifier]
	at com.dexels.navajo.server.Dispatcher.handle(Dispatcher.java:640)[23:com.dexels.navajo.core:5.3.63.qualifier]
	at com.dexels.navajo.server.LocalClientDispatcherWrapper.handleInternal(LocalClientDispatcherWrapper.java:79)[23:com.dexels.navajo.core:5.3.63.qualifier]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.execute(TmlContinuationRunner.java:122)[44:com.dexels.navajo.listeners.continuations:2.1.25.qualifier]
	at com.dexels.navajo.server.listener.http.continuation.TmlContinuationRunner.run(TmlContinuationRunner.java:186)[44:com.dexels.navajo.listeners.continuations:2.1.25.qualifier]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)[:]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)[:]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)[:]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)[:]
	at java.base/java.lang.Thread.run(Thread.java:834)[:]
Caused by: java.lang.ClassCastException: class [Lcom.dexels.navajo.adapter.RowMap; cannot be cast to class java.util.List ([Lcom.dexels.navajo.adapter.RowMap; is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6cfeb5f3; java.util.List is in module java.base of loader 'bootstrap')
	at matchreport.InitTest.execute_sub0(InitTest.java:108)
	at matchreport.InitTest.execute(InitTest.java:78)
	at com.dexels.navajo.mapping.CompiledScript.run(CompiledScript.java:423)[23:com.dexels.navajo.core:5.3.63.qualifier]
	at com.dexels.navajo.server.GenericHandler.doService(GenericHandler.java:429)[23:com.dexels.navajo.core:5.3.63.qualifier]
	... 11 more
````

**Comment by kharybdys** [comment]
Even better would be to allow this version:
```
package com.dexels.navajo.adapter;

import java.util.ArrayList;
import java.util.List;

import com.dexels.navajo.script.api.Access;
import com.dexels.navajo.script.api.Mappable;
import com.dexels.navajo.script.api.MappableException;
import com.dexels.navajo.script.api.UserException;

public class CountAdapter implements Mappable 
{
    private int rowCount = -1;

    @Override
    public void load( Access access ) throws MappableException, UserException
    {
    }

    @Override
    public void store() throws MappableException, UserException 
    {
    }

    @Override
    public void kill() 
    {
    }
    
    public void setRowCount( int rowCount )
    {
        this.rowCount = rowCount;
    }

    public List<RowMap> getRows() throws UserException
    {
        if( rowCount < 0 )
        {
            throw new UserException( "Specify number of rows to generate first" );
        }
        else
        {
            List<RowMap> rows = new ArrayList<RowMap>();
            for( int i = 0; i < rowCount; i++ ) 
            {
                rows.add( new RowMap( i ) );
            }
            return rows;
        }
    }
}
```
But that gives the following exception:
```
Caused by: com.dexels.navajo.script.api.MappingException: Could not find method in Mappable object: getRowNumber in object: [com.dexels.navajo.adapter.RowMap@60fa1eda, com.dexels.navajo.adapter.RowMap@6126d4b7, com.dexels.navajo.adapter.RowMap@66061d84, com.dexels.navajo.adapter.RowMap@1fb1a973, com.dexels.navajo.adapter.RowMap@2f8d6891, com.dexels.navajo.adapter.RowMap@785982bb, com.dexels.navajo.adapter.RowMap@2e655a09, com.dexels.navajo.adapter.RowMap@3c0d8487, com.dexels.navajo.adapter.RowMap@7880aa77, com.dexels.navajo.adapter.RowMap@4c78b386]
	at com.dexels.navajo.script.api.MappableTreeNode.getMethodReference(MappableTreeNode.java:254)[57:com.dexels.navajo.api:3.2.29.qualifier]
	at com.dexels.navajo.mapping.MappingUtils.getAttributeObject(MappingUtils.java:799)[23:com.dexels.navajo.core:5.3.63.qualifier]
	at com.dexels.navajo.mapping.MappingUtils.getAttributeValue(MappingUtils.java:838)[23:com.dexels.navajo.core:5.3.63.qualifier]
	at com.dexels.navajo.parser.compiled.ASTMappableNode.maybeGetMapAttribute(ASTMappableNode.java:44)
```

**Comment by kharybdys** [comment]
@aschoneveld This is what I was talking about earlier today.

**Comment by aschoneveld** [comment]
@kharybdys : this is in fact a very useful feature. 
Also note that implementing Mappable is not required if you don't want to do any lifecycle related, such as cleaning up stuff after the adapter has been used.
Implementing this feature requires changing TslCompiler since it currently only supports Java array type as a result of a "getter".
